# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_compiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiler',
            name='create_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.employee'),
        ),
    ]
