# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_employee_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='server_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=30)),
                ('server_ip', models.CharField(max_length=20)),
                ('image_id', models.CharField(max_length=50)),
                ('container_id', models.CharField(max_length=50)),
                ('container_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='permission',
            field=models.IntegerField(null=True),
        ),
    ]
