# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:51
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compile_name', models.CharField(max_length=30)),
                ('compile_ip', models.CharField(max_length=20)),
                ('create_user_id', models.IntegerField(verbose_name=builtins.id)),
                ('repertory_dir', models.CharField(max_length=30)),
            ],
        ),
    ]
