# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_auto_20170727_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='node_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=30)),
                ('node_ip', models.CharField(max_length=20)),
                ('code_dir', models.CharField(max_length=30)),
                ('create_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.employee')),
            ],
        ),
    ]
